P.register("cvfVersion",function(){return{version:"0.1.0.0-2019-05-25"}});
P.when("A","cvfFormDataGenerator","ready").register("cvf-account-switcher",function(a,l){function h(b,c){b.preventDefault();var e=l.retrieveFormData(b.target),f=e.inputData.serializeArray();f.push(m(b.target));a.ajax(window.location.protocol+"//"+window.location.host+e.requestPath,{method:"POST",params:f,success:c,error:n})}function m(d){d=b(d);var c=d.attr("name");c||(c=d.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var e=d.attr("value");e||(e=d.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));
return{name:c,value:e}}function n(b,c,e){a.trigger(t.error,e)}function g(d){var c=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(d);if(null!==c){d=c[1];d=b.trim(d);var e=d.length;if(1!==e){for(var f=d.charAt(0),a=0;a<e-2;a++)f+="*";d=f+=d.charAt(e-1)}d+="@";f=c[2];f=b.trim(f);e=f.length;f=f.charAt(0);for(a=0;a<e-1;a++)f+="*";return d+f+c[3]}c=b.trim(d);d=c.length;if(!(4>=d)){e="";for(f=0;f<d-4;f++)e+="*";c=e+c.substr(d-4,d-1)}return c}function p(){0===b(".cvf-account-switcher-check-mark:visible").length&&
(b(".cvf-account-switcher-check-mark-area").remove(),b(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}var b=a.$,t={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"};(function(){var a=b("#ap-account-switcher-container")[0],c=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==c){var e=new c(function(b){for(var a=0;a<b.length;a++)if(null!==b[a].addedNodes){p();
e.disconnect();break}});e.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){b(".cvf-account-switcher-sign-out-link").live("click",function(d){h(d,function(c){if(c.redirectUrl)window.location=c.redirectUrl,a.trigger("cvf:account_switcher","redirectOnSignOut");else if(c.succeeded){var e="."+b(d.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];b(e+"-hide").hide();b(e+"-name").text(b("#cvf-account-switcher-sign-out-replace-text").text());b(e+
"-claim").text(g(b(e+"-claim").text()));b(e+"-image").replaceWith(b("<div />").append(b("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());b(e+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");c=c.switchedAccountId;void 0!==c&&b(".cvf-account-switcher-account-group-"+c+"-check-mark").show();p()}else a.trigger(t.error,c)})})})()});
P.when("A","cvfVersion","cvfFormDataGenerator","ready").register("cvf",function(a,l,h){function m(m){function d(b){"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",k.options.widgetMetricsScope,{wb:1});k.options.spinnerTarget&&k.options.spinnerTarget.hide();b.hasOwnProperty("error")?a.trigger(r.error,b.error):b.redirectUrl?window.location=b.redirectUrl:b.redirect?(a.trigger(r.success,b.token,b.status,b.redirect),k.options.autoDestroy?k.destroy():(g(".cvf-widget-alert").hide(),
b.status?g(".cvf-widget-status-success").show():g(".cvf-widget-status-error").show(),v()),a.trigger("cvf:verification:complete",b.status),q.find(".cvf-widget-btn").unbind("click",c),q.find(".cvf-widget-btn-val").unbind("click",c),a.off(r.success),a.off(r.error)):(q.html(b.replace(/<form/g,"<div").replace(/<\/form/g,"</div")),f())}function c(b,e){b.preventDefault();g(".cvf-widget-alert").hide();k.options.spinnerTarget&&k.options.spinnerTarget.show();var c=h.retrieveFormData(b.target),f=c.inputData.serializeArray();
e&&f.push(h.getNameValue(b.target));a.ajax(w+c.requestPath,{method:"POST",params:f,success:d,error:u})}function e(b){13===b.keyCode&&c(b)}function f(){q.find(".cvf-widget-btn").click(function(b){c(b,!1)});q.find(".cvf-widget-btn-val").click(function(b){c(b,!0)});q.find('input[name="code"]').focus().keypress(e)}function n(b){return function(e,c,f){"timeout"!==c||3<=x?a.trigger(r.error,f):a.delay(b,10*x++)}}function u(b,e,c){k.options.spinnerTarget&&k.options.spinnerTarget.hide();a.trigger(r.error,
c)}function v(){g.each(q.find("input"),function(b,e){var a=g(e);a.attr("disabled","disabled");a.hasClass("a-input-text")?a.addClass("a-form-disabled"):a.hasClass("a-button-input")?a.closest(".a-button").addClass("a-button-disabled"):a.closest(".a-input-text-wrapper").length&&a.closest(".a-input-text-wrapper").addClass("a-form-disabled")});g.each(q.find("a"),function(b,a){var e=g(a);e.hasClass("cvf-widget-link-disable-target")&&e.addClass("cvf-link-disabled")})}var k=this;b++;var r={success:"cvf:"+
b+":success",error:"cvf:"+b+":error"};k.options={};g.extend(k.options,p,m);(function(b){if(1!==g(b.target).length)throw Error("The CVF widget requires a unique element.");if(!g.isFunction(b.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!g.isFunction(b.onError))throw Error("The CVF widget requires an error callback function.");})(k.options);var w=k.options.server,q=g(k.options.target);a.on(r.success,k.options.onSuccess);a.on(r.error,k.options.onError);k.start=function(){if(0===
g.trim(k.options.requestToken).length)throw Error("The CVF widget requires a request token.");var b=w+"/ap/cvf/request.embed",e=k.options.requestToken,c=k.options.requestArbToken,f={};0===g.trim(c).length?f.requestToken=e:f.arb=c;f.CVFVersion=l.version;f.AUIVersion=P.AUI_BUILD_DATE;"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uet("bb",k.options.widgetMetricsScope,{wb:1});a.ajax(b,{method:"GET",params:f,success:d,error:n(k.start)})};k.destroy=function(){q.html("")};
f();var x=0;k.options.autoStart&&k.start()}function n(b){return new m(b)}var g=a.$,p={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,onError:void 0,spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0},b=0;a.on("cvf:verification:request",function(b){var d=g("#"+b),c=d.data("token"),e=d.data("spinnerId"),e=g("#"+e);n({target:d,spinnerTarget:e,requestToken:c,onSuccess:function(e,c,d){a.trigger("cvf:verification:complete:"+b,e,c,d)},onError:function(e){a.trigger("cvf:verification:error:"+
b,e)},autoStart:!0,autoDestroy:!1})});return{create:n}});P.when("A","cvf","ready").execute(function(a,l){var h=a.$;h(document).ready(function(){function a(b,d,c){window.location=c;console.log("Client Side: "+b)}function n(b){console.log(b)}var g=h(".cvf-widget-spinner"),p=h("#cvf-widget-content");if(1===p.length){var b=h('[name="requestToken"]').first().attr("value");l.create({target:p,spinnerTarget:g,requestToken:b,onSuccess:a,onError:n,autoStart:!1})}})});
P.when("A").execute(function(a){a.declarative("auth-popup","click",function(a){var h=a.data;a=a.$target.closest("a")[0];(h=window.open(a.href,a.target,h.windowOptions))&&h.focus()})});P.when("A","cvfFormDataGenerator","ready").execute(function(a,l){});
P.when("A","cvfFormDataGenerator","ready").execute(function(a,l){var h=a.$;h(".cvf-widget-btn-val").click(function(a){var n=h(a.target).closest(".cvf-widget-form");a=l.getNameValue(h(a.target));n.append('<input type="hidden" name="'+a.name+'" value="'+a.value+'">').submit()})});
P.when("A","ready").register("cvfFormDataGenerator",function(a){var l=a.$;return{retrieveFormData:function(a){a=l(a).closest(".cvf-widget-form");return{requestPath:a.data("use-only-form-action")?a.attr("action"):"/ap/cvf/"+a.attr("action")+".embed",inputData:a.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:a}},getNameValue:function(a){a=l(a);var m=a.attr("name");m||(m=a.closest(".cvf-widget-btn-val").attr("data-name"));var n=a.attr("value");n||(n=a.closest(".cvf-widget-btn-val").attr("data-value"));
return{name:m,value:n}}}});P.when("A","ready").register("codeResendTimer",function(a){function l(h,m,n){var g=(new Date).getTime(),p=setInterval(function(){var b=(new Date).getTime()-g,b=h-b;if(0>=b)clearInterval(p),a.$("#timer").html(n);else{var b=Math.floor(b/1E3),l=m.split(" +timeleft+ "),b=l[0].split('"').join("")+b+l[1].split('"').join("");a.$("#timer").html(b)}},100)}return{createTimer:function(a,m,n){return new l(a,m,n)}}});